spring.application.name=aws-basic
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nextgeninfotech26@gmail.com
spring.mail.password=rjwv gkfg gmob gsks

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true